export { default as logo } from '../assets/images/logo.webp';
export { default as classesandevents } from '../assets/images/classes-and-events.webp';
export { default as merch } from '../assets/images/merchs.webp';
export { default as bg } from '../assets/images/bg.webp';
export { default as productions } from '../assets/images/manoloka-description-01.webp';
export { default as productionsWebm } from '../assets/videos/manoloka.WEBM';
export { default as productionsMp4 } from '../assets/videos/manoloka.mp4';
export { default as headlogo } from '../assets/images/headlogo.webp';
export { default as lession } from '../assets/images/SOON.webp';